name: university_qa_system
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  uuid: ^4.5.2
  logger: ^2.6.2
  fpdart: ^1.2.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.3
  flutter_dotenv: ^6.0.0
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  internet_connection_checker_plus: ^2.9.1+1
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env